### PR TITLE
Update APIs and fix deprecations for 2018.3 support.

### LINKED ISSUE #80: Test and switch development to the latest 2018.3 IDEs
Make sure it's fully compatible given issues with Cloud Tools.

### PR DESCRIPTION
**Pull request by ivanporty**
Fixes #80.

A number of incompatible changes have been made in 2018.3, in particular with nullability of actions, generics for RunConfigBase and deprecation of project base directory property. This all has been addressed for plugin to compile and work on 2018.3

### CODE REVIEW

**Comment by etanshaul** [comment]
or, is the idea that we'll support only 2018.3+ ?

**Comment by ivanporty** [comment]
We won't be able to build with previous versions apparently, but hopefully still support previous ones - trying to test this out on 2018.2 and earlier.

**Comment by etanshaul** [comment]
cool. I think its perfectly ok to support 2018.3 + if need be.

**Comment by ivanporty** [comment]
Confirmed - it's still working on 2018.2 family IDEs.

File: skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldCommandLineState.kt [hunk 1]
```diff
@@ -66,11 +67,13 @@ class SkaffoldCommandLineState(
...
         )
 
+        val workingDirectory: File? = File(projectBaseDir.path)
+
         val skaffoldProcess = SkaffoldExecutorService.instance.executeSkaffold(
             SkaffoldExecutorSettings(
                 executionMode,
                 skaffoldConfigurationFilePath,
-                workingDirectory = File(environment.project.basePath),
+                workingDirectory = workingDirectory,
```
Comment (etanshaul) [inline skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldCommandLineState.kt]: why not just keep it inline instead of defining `workingDIrectory`?

Comment (ivanporty) [reply skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldCommandLineState.kt]: Agree, remainder of refactoring
