### PR TITLE
Fix write block by using PSI data when available for proper sync

### LINKED ISSUE #100: Skaffold YAML changes not immediately seen by Skaffold tools if not explicitly saved
When adding a new change into Skaffold YAML file, for example, new profile or an image change, or even adding a new Skaffold YAML file, tools that rely on file content - Skaffold file search or YAML content may not see the change right away unless file is explicitly saved by `Ctrl-S`. 

We need to find a way to commit the writes or flush the cache before the actions that need up-to-date Skaffold YAML contents.

### LINKED ISSUE #114: Write happening outside of EDT for setProject
Just ran a skaffold dev config, then stopped it, and noticed this IDE error:
```
java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState:{[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog0,734,1028,1092x698,invalid,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Run/Debug Configurations,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,5,25,1082x668,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]]}
  known modalities:
    ModalityState.NON_MODAL, writingAllowed=true;
    ModalityState:{}, writingAllowed=true;
    ModalityState:{[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog0,734,1028,1092x698,invalid,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Run/Debug Configurations,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,5,25,1082x668,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]]}, writingAllowed=true
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:232)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:289)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:281)
	at com.google.container.tools.skaffold.run.ui.SkaffoldFilesComboBox$setProject$1$1.run(SkaffoldFilesComboBox.kt:49)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:670)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:683)
	at com.google.container.tools.skaffold.run.ui.SkaffoldFilesComboBox.setProject(SkaffoldFilesComboBox.kt:49)
	at com.google.container.tools.skaffold.run.ui.BaseSkaffoldSettingsEditor.resetEditorFrom(BaseSkaffoldSettingsEditor.kt:108)
	at com.google.container.tools.skaffold.run.ui.BaseSkaffoldSettingsEditor.resetEditorFrom(BaseSkaffoldSettingsEditor.kt:43)
	at com.intellij.openapi.options.SettingsEditor.lambda$resetFrom$0(SettingsEditor.java:73)
	at com.intellij.openapi.options.SettingsEditor.bulkUpdate(SettingsEditor.java:80)
	at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:73)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.resetEditorFrom(ConfigurationSettingsEditor.java:287)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.resetEditorFrom(ConfigurationSettingsEditor.java:271)
	at com.intellij.openapi.options.CompositeSettingsEditor.resetEditorFrom(CompositeSettingsEditor.java:52)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.resetEditorFrom(ConfigurationSettingsEditorWrapper.java:98)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.resetEditorFrom(ConfigurationSettingsEditorWrapper.java:25)
	at com.intellij.openapi.options.SettingsEditor.lambda$resetFrom$0(SettingsEditor.java:73)
	at com.intellij.openapi.options.SettingsEditor.bulkUpdate(SettingsEditor.java:80)
	at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:73)
```

### PR DESCRIPTION
**Pull request by ivanporty**
Fixes #114, different approach to fix #100.

Instead of saving files which is not allowed (along with file syncs and any other cache/edit save operations) from the modal dialogs, use PSI file content that contains the latest up-to-date memory representation of the file and the latest edits.

### CODE REVIEW

File: skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldYamlConfiguration.kt [hunk 1]
```diff
@@ -16,25 +16,45 @@
...
 
     init {
+        // attempt to use in-memory data of PSI if exists and project is set first, or if not,
+        // fallback to directly parsing YAML file with VirtualFile
         val yamlLoader = Yaml()
-        skaffoldYamlMap.putAll(
-            yamlLoader.load(ByteArrayInputStream(skaffoldYamlFile.contentsToByteArray()))
-        )
+        var loadedWithPsiFile = false
+        if (project != null) {
```
Comment (etanshaul) [inline skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldYamlConfiguration.kt]: would the project ever be expected to be null? if not, could we just use this path?

Comment (ivanporty) [reply skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldYamlConfiguration.kt]: For now yes, to use the testing with Virtual Files, since setting up the same amount of testing with just PsiFile seems to be a large re-work since it always involve quite complex PsiManager (per project, not global service) and setting up at least some degree of PsiElements (root element with Document and maybe something else).

Comment (etanshaul) [reply skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldYamlConfiguration.kt]: I think you can test it by having the test file as an actual file in the resource directory: see https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/6929429dde951d404af995509d114b1d4265e58a/app-engine/java/testSrc/com/google/cloud/tools/intellij/appengine/java/project/DefaultAppEngineProjectServiceTest.java#L118

but lgtm for now

Comment (ivanporty) [reply skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldYamlConfiguration.kt]: Ah looks good, we can have this as a fix for exception, and I'll tackle change of Virtual Files to PSI Files next, might use the new test annotation for it as well.
